services:
  vector-db:
    image: chromadb/chroma
    container_name: chromadb_container
    environment:
      - ANONYMIZED_TELEMETRY=False
    networks:
      - timepledge_network
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/data # Production on server
      - ./chromadb_data:/data # Dev on machine (remove for production)

  backend:
    image: backend_image
    build:
      context: ./chatbot_backend
      dockerfile: Dockerfile.backend
    container_name: backend_container
    networks:
      - timepledge_network
    depends_on:
      - vector-db

  frontend:
    image: frontend_image
    build:
      context: ./chatbot_frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    networks:
      - timepledge_network
    depends_on:
      - backend

networks:
  timepledge_network:
    name: timepledge_network

volumes:
  chromadb_data:
    name: chromadb_data
